console.log("This is tut41");
  //try and catch error handling

// let a = "Biplab";
//  a = undefined;

//  if (a != undefined) {
//     throw new Error("This is not undifined");
//  } 
//  else {
//    console.log("This is undifined");   
//  }



try{
//  jxhgjsdhcujd
//  null.console
 console.log("We are inside try block");   
  func1();
} catch (error) {
    console.log(error);
    console.log(error.name);
    console.log(error.message);
    console.log("Are you ok!");
} finally{
    console.log("Finally we will run this");
};